name: Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/**
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 4 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Audit"
        run: |
          .github/scripts/cargo-audit.sh
