name: Rust
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Fmt"
        run: |
          .github/scripts/cargo-fmt.sh

      - name: "Clippy"
        run: |
          .github/scripts/cargo-clippy.sh

      - name: "Test"
        run: |
          .github/scripts/cargo-test.sh
